### ISSUE TITLE
Resolve problems with test and main program

### ISSUE THREAD

**Issue by marcosstefani** [marcosstefani/flute#2]
We have problems in the use of the package because, to perform the tests we need to put the command sys.path.append ('..') and this impacts directly in the use of the packages, because to upload to the pip without errors we need to be changing the import for example, from:

from utility import create_dir, create_file, tabs, caps
for
from .util import create_dir, create_file, tabs, caps

We need to solve this problem

**Comment by Brcrwilliams** [comment]
What if you moved the tests outside of the flute package and then do
```python
from flute.util import create_dir, create_file, tabs, caps
```

**Comment by marcosstefani** [comment]
@Brcrwilliams for me, any attempt is valid. Feel free.

**Comment by iflare3g** [comment]
I'm working on it 👍

**Comment by marcosstefani** [comment]
Thank you

**Comment by marcosstefani** [comment]
https://github.com/marcosstefani/flute/pull/5
