### ISSUE TITLE
Implement autocreate MVCS

### ISSUE THREAD

**Issue by marcosstefani** [marcosstefani/flute#3]
Implement a command to create the Model, View, Controller, and Service.

**Comment by iflare3g** [comment]
Do you mean creating them inside files folder ?

**Comment by marcosstefani** [comment]
Yes @iflare3g, run the new_app () method that gets inside __init__.py and see that it automatically creates the entire structure of the app. In this case, the model is already being created in new_model (). And this Issue tries to complete the mvcs () method, see that it already creates the model, needs to create a view, controller and a service. See examples of test usage.

**Comment by iflare3g** [comment]
Cool! Just to have a clearer idea: will view, controller and service files be empty or you wanna have some first line comment ( e.g. Django views.py has "creates your views here" as first line comment )  ?  @marcosstefani

**Comment by marcosstefani** [comment]
I thought about making it look like Ruby on Rails, create a basic View. The idea is not to do something like Django because it already does. I plan on bringing something new, similar to Rails.

**Comment by iflare3g** [comment]
I'm working on it, as soon as I can, I will make a PR.
At the moment, new create_controller() creates controller.py inside app/controller folder and it has just a first line comment

**Comment by marcosstefani** [comment]
Thank you! ;)

**Comment by marcosstefani** [comment]
https://github.com/marcosstefani/flute/pull/5#pullrequestreview-165129683
